### ISSUE TITLE
PlaneWaveBasis method error

### ISSUE THREAD

**Issue by sqr00t** [mfherbst/juliacon_dft_workshop#1]
Following the 2_Periodic_problems_and_plane_waves.ipynb tutorial.

MethodError: no method matching PlaneWaveBasis(::Model{Float64}; Ecut=300, kgrid=[1, 1, 1])
Closest candidates are:
  PlaneWaveBasis(::Model{T}, ::T, ::Array{Kpoint{T}, 1}, ::Vector{T}, ::Vector{Vector{Tuple{StaticArrays.SMatrix{3, 3, Int64, 9}, StaticArrays.SVector{3, Float64}}}}, ::MPI.Comm, ::Vector{Int64}, ::Tuple{Int64, Int64, Int64}, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Vector{Any}, ::Vector{Tuple{StaticArrays.SMatrix{3, 3, Int64, 9}, StaticArrays.SVector{3, Float64}}}) where T<:Real at C:\Users\Solomon\.julia\packages\DFTK\V8lWf\src\PlaneWaveBasis.jl:53 got unsupported keyword arguments "Ecut", "kgrid"
  PlaneWaveBasis(::Model, ::Number; kgrid, kshift, use_symmetry, kwargs...) at C:\Users\Solomon\.julia\packages\DFTK\V8lWf\src\PlaneWaveBasis.jl:280
  PlaneWaveBasis(::Model{T}, ::Number, ::AbstractVector{T} where T, ::Any) where T<:Real at C:\Users\Solomon\.julia\packages\TimerOutputs\ZQ0rt\src\TimerOutput.jl:213 got unsupported keyword arguments "Ecut", "kgrid"
  ...

Stacktrace:
 [1] top-level scope
   @ In[3]:26
 [2] eval
   @ .\boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1094

**Comment by mfherbst** [comment]
The interface used in the notes was introduced in DFTK 0.3.9, see `1_Installation.ipynb`. Please check you have this version installed.

**Comment by sqr00t** [comment]
Version mismatch explains it. I followed everything in 1_Installtion.ipynb, and tests check out, but DFTK was stuck on v0.2.0 due to package incompatibility.

Removing the following package then allowed install of DFTK up to latest (v0.3.10):
-Strategems v0.3.0

**Comment by mfherbst** [comment]
Perfect. I'll close this then.
